language: php
php:
    - 5.5
    - 5.4
    - hhvm

before_script:


script: 

    - phpunit --bootstrap test/config.php  test

after_script:
    - php mosbth/bin/coveralls -v
    - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

notifications:
    irc: "irc.freenode.org#dbwebb"



